services:

  app1:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - myapp:latest
        - myapp:1.0
    image: 'myapp:latest'
    container_name: 'app1'
    ports:
      - '8080:8080'
    environment:
      TEST_VAR1: 1

  app2:
    image: 'myapp:latest'
    container_name: 'app2'
    ports:
      - '8081:8080'
    environment:
      TEST_VAR1: 2
    depends_on:
      - app1